sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.1
  - 2.2.6
  - 2.3.1
  - 2.4.0
  - jruby-9.1.13.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
