sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler
rvm:
  - 1.9
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.13.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.13.0
  fast_finish: true
